// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Service;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Repo.StudentRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

@Service
public class StudentServices_deleteStudent_9983cca4b5_Test {

    @Autowired
    private StudentRepo repo;

    @BeforeEach
    public void setup() {
        repo = Mockito.mock(StudentRepo.class);
    }

    @Test
    public void testDeleteStudent_SuccessScenario() {
        
        // TODO: Replace "testId" with the actual ID of the student you want to delete.
        String testId = "testId";
        
        Mockito.doNothing().when(repo).deleteById(testId);
        
        repo.deleteById(testId);
        
        Mockito.verify(repo, Mockito.times(1)).deleteById(testId);
    }

    @Test
    public void testDeleteStudent_FailureScenario() {
        
        // TODO: Replace "invalidId" with the ID of a student that does not exist in the database.
        String invalidId = "invalidId";
        
        Mockito.doThrow(new IllegalArgumentException()).when(repo).deleteById(invalidId);
        
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            repo.deleteById(invalidId);
        });
        
        Mockito.verify(repo, Mockito.times(1)).deleteById(invalidId);
    }
}
