// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Service;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Repo.StudentRepo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class StudentServices_getStudentByID_59fd5b1864_Test {

    @Mock
    private StudentRepo repo;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void testGetStudentByID_Exists() {
        Student mockStudent = new Student();
        mockStudent.set_id("123");
        mockStudent.setStudentname("John Doe");
        mockStudent.setStudentaddress("123 Main St");
        mockStudent.setMobile("1234567890");

        when(repo.findById(anyString())).thenReturn(Optional.of(mockStudent));

        Student student = repo.findById("123").get();

        assertNotNull(student);
        assertEquals("123", student.get_id());
        assertEquals("John Doe", student.getStudentname());
        assertEquals("123 Main St", student.getStudentaddress());
        assertEquals("1234567890", student.getMobile());
    }

    @Test
    void testGetStudentByID_NotExists() {
        when(repo.findById(anyString())).thenReturn(Optional.empty());

        assertThrows(RuntimeException.class, () -> repo.findById("123").get());
    }
}
