// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Service;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Repo.StudentRepo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class StudentServices_getStudentByID_59fd5b1864_Test {

    @Mock
    private StudentRepo repo;

    @InjectMocks
    private StudentServices studentServices;

    private Student student;

    @BeforeEach
    public void setup() {
        student = new Student();
        student.set_id("123");
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");
    }

    @Test
    public void testGetStudentByID_Success() {
        when(repo.findById("123")).thenReturn(Optional.of(student));

        Student result = studentServices.getStudentByID("123");

        assertEquals("123", result.get_id());
        assertEquals("John Doe", result.getStudentname());
        assertEquals("123 Street", result.getStudentaddress());
        assertEquals("1234567890", result.getMobile());
    }

    @Test
    public void testGetStudentByID_Failure() {
        when(repo.findById("123")).thenReturn(Optional.empty());

        assertThrows(RuntimeException.class, () -> studentServices.getStudentByID("123"));
    }
}
