// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Service;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Repo.StudentRepo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@SpringBootTest
public class StudentServices_listAll_720f08e71b_Test {

    @InjectMocks
    private StudentServices studentServices;

    @Mock
    private StudentRepo repo;

    private Student student1;
    private Student student2;

    @BeforeEach
    public void setup() {
        student1 = new Student();
        student1.set_id("1");
        student1.setStudentname("John");
        student1.setStudentaddress("123 Street");
        student1.setMobile("1234567890");

        student2 = new Student();
        student2.set_id("2");
        student2.setStudentname("Jane");
        student2.setStudentaddress("456 Avenue");
        student2.setMobile("0987654321");
    }

    @Test
    public void testListAll() {
        List<Student> expectedStudents = Arrays.asList(student1, student2);
        when(repo.findAll()).thenReturn(expectedStudents);

        Iterable<Student> actualStudents = studentServices.listAll();

        assertEquals(expectedStudents, actualStudents);
    }

    @Test
    public void testListAllWhenNoStudents() {
        when(repo.findAll()).thenReturn(Arrays.asList());

        Iterable<Student> actualStudents = studentServices.listAll();

        assertEquals(Arrays.asList(), actualStudents);
    }
}
