// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Service;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Repo.StudentRepo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.anyString;

@SpringBootTest
public class StudentServices_deleteStudent_9983cca4b5_Test {

    @Autowired
    @InjectMocks
    private StudentServices studentServices;

    @Mock
    private StudentRepo studentRepo;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDeleteStudent_success() {
        String id = "123";
        studentServices.deleteStudent(id);
        verify(studentRepo, times(1)).deleteById(id);
    }

    @Test
    public void testDeleteStudent_failure() {
        String id = "";
        studentServices.deleteStudent(id);
        verify(studentRepo, times(0)).deleteById(anyString());
    }
}
