// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Service;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Repo.StudentRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@SpringBootTest
public class StudentServices_listAll_720f08e71b_Test {

    @Autowired
    private StudentServices studentServices;

    @MockBean
    private StudentRepo repo;

    @Test
    public void testListAll() {
        Student student1 = new Student("1", "John Doe", "123 Street", "1234567890");
        Student student2 = new Student("2", "Jane Doe", "456 Street", "0987654321");

        when(repo.findAll()).thenReturn(Arrays.asList(student1, student2));

        Iterable<Student> result = studentServices.listAll();
        List<Student> resultList = (List<Student>) result;

        assertThat(resultList.size()).isEqualTo(2);
        assertThat(resultList.get(0)).isEqualTo(student1);
        assertThat(resultList.get(1)).isEqualTo(student2);
    }

    @Test
    public void testListAllWhenNoStudents() {
        when(repo.findAll()).thenReturn(Arrays.asList());

        Iterable<Student> result = studentServices.listAll();
        List<Student> resultList = (List<Student>) result;

        assertThat(resultList.size()).isEqualTo(0);
    }
}
