// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Service;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Repo.StudentRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.mockito.Mockito.times;

@SpringBootTest
public class StudentServices_deleteStudent_9983cca4b5_Test {

    @Autowired
    private StudentServices studentServices;

    @MockBean
    private StudentRepo studentRepo;

    @Test
    public void testDeleteStudentWhenIdExists() {
        String id = "testId";
        Mockito.doNothing().when(studentRepo).deleteById(id);
        studentServices.deleteStudent(id);
        Mockito.verify(studentRepo, times(1)).deleteById(id);
    }

    @Test
    public void testDeleteStudentWhenIdDoesNotExist() {
        String id = "nonExistingId";
        // TODO: Replace with actual exception thrown when id does not exist.
        Mockito.doThrow(new RuntimeException()).when(studentRepo).deleteById(id);
        try {
            studentServices.deleteStudent(id);
        } catch (Exception e) {
            // Expected exception
        }
        Mockito.verify(studentRepo, times(1)).deleteById(id);
    }
}
