// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Student_toString_ceffa8036e_Test {

    private Student student;

    @BeforeEach
    public void setup() {
        student = new Student();
        student.set_id("1");
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Main St");
        student.setMobile("1234567890");
    }

    @Test
    public void testToString() {
        String expected = "Student{" +
                "_id='1'" +
                ", studentname='John Doe'" +
                ", studentaddress='123 Main St'" +
                ", mobile='1234567890'" +
                '}';
        Assertions.assertEquals(expected, student.toString());
    }

    @Test
    public void testToString_EmptyFields() {
        student = new Student();
        String expected = "Student{" +
                "_id='null'" +
                ", studentname='null'" +
                ", studentaddress='null'" +
                ", mobile='null'" +
                '}';
        Assertions.assertEquals(expected, student.toString());
    }
}
