// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Student_setMobile_14d728d95e_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = Mockito.mock(Student.class);
    }

    @Test
    public void testSetMobile_success() {
        String mobile = "1234567890";
        Mockito.doAnswer(invocation -> {
            String argument = invocation.getArgument(0);
            assertEquals(mobile, argument);
            return null;
        }).when(student).setMobile(Mockito.anyString());

        student.setMobile(mobile);
    }

    @Test
    public void testSetMobile_failure() {
        String wrongMobile = "WrongMobile";
        Mockito.doAnswer(invocation -> {
            String argument = invocation.getArgument(0);
            assertEquals(wrongMobile, argument);
            return null;
        }).when(student).setMobile(Mockito.anyString());

        student.setMobile("1234567890");
    }
}
