// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.util.Assert;

public class Student_set_id_b8adefff49_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetIdWithValidId() {
        String validId = "1234";
        student.set_id(validId);
        Assert.isTrue(student.get_id().equals(validId), "Failed to set valid id");
    }

    @Test
    public void testSetIdWithNullId() {
        String nullId = null;
        student.set_id(nullId);
        Assert.isTrue(student.get_id() == null, "Failed to set null id");
    }
}
