// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_set_id_b8adefff49_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetId() {
        String expectedId = "12345";
        student.set_id(expectedId);
        assertEquals(expectedId, student.get_id(), "The expected ID does not match the actual ID");
    }

    @Test
    public void testSetIdWithNull() {
        String expectedId = null;
        student.set_id(expectedId);
        assertEquals(expectedId, student.get_id(), "The expected ID does not match the actual ID");
    }
}
