// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

@Document(collection = "Student")
public class Student_158c71b90f_Test {

    @Id
    private String _id;
    private String studentname;
    private String studentaddress;
    private String mobile;

    public Student (String _id,String studentname,String studentaddress, String mobile){
        this._id=_id;
        this.studentname = studentname;
        this.studentaddress = studentaddress;
        this.mobile= mobile;
    }

    @Test
    public void testStudentCreation() {
        String id = "123";
        String name = "John Doe";
        String address = "123 Main St";
        String mobile = "1234567890";
        Student student = new Student(id, name, address, mobile);
        assertEquals(id, student._id);
        assertEquals(name, student.studentname);
        assertEquals(address, student.studentaddress);
        assertEquals(mobile, student.mobile);
    }

    @Test
    public void testStudentCreationWithNullValues() {
        String id = null;
        String name = null;
        String address = null;
        String mobile = null;
        Student student = new Student(id, name, address, mobile);
        assertEquals(id, student._id);
        assertEquals(name, student.studentname);
        assertEquals(address, student.studentaddress);
        assertEquals(mobile, student.mobile);
    }
}
