// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Student_getMobile_e15a571bc1_Test {

    @Test
    public void testGetMobileSuccess() {
        // TODO: Create a Student object and set mobile value
        Student student = new Student();
        student.setMobile("1234567890");

        String expectedMobile = "1234567890";
        String actualMobile = student.getMobile();

        Assertions.assertEquals(expectedMobile, actualMobile, "The expected mobile number does not match the actual mobile number");
    }

    @Test
    public void testGetMobileFailure() {
        // TODO: Create a Student object and do not set mobile value
        Student student = new Student();

        String expectedMobile = null;
        String actualMobile = student.getMobile();

        Assertions.assertEquals(expectedMobile, actualMobile, "The expected mobile number does not match the actual mobile number");
    }
}
