// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setStudentname_e4841ead99_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetStudentName() {
        String expectedName = "John Doe";
        student.setStudentname(expectedName);
        assertEquals(expectedName, student.getStudentname());
    }

    @Test
    public void testSetStudentName_EmptyString() {
        String expectedName = "";
        student.setStudentname(expectedName);
        assertEquals(expectedName, student.getStudentname());
    }
}
