// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
public class Student_getMobile_e15a571bc1_Test {

    @InjectMocks
    private Student student;

    @Test
    public void testGetMobileSuccess() {
        String expectedMobileNumber = "1234567890";
        student.setMobile(expectedMobileNumber);
        String actualMobileNumber = student.getMobile();
        Assertions.assertEquals(expectedMobileNumber, actualMobileNumber, "Mobile number should match");
    }

    @Test
    public void testGetMobileFailure() {
        String expectedMobileNumber = "0987654321";
        student.setMobile("1234567890");
        String actualMobileNumber = student.getMobile();
        Assertions.assertNotEquals(expectedMobileNumber, actualMobileNumber, "Mobile number should not match");
    }
}
