// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Student_getStudentaddress_a74194294e_Test {

    @MockBean
    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testGetStudentAddress_ValidAddress() {
        // TODO: Replace "123 Main St" with the actual student address
        student.setStudentaddress("123 Main St");
        assertEquals("123 Main St", student.getStudentaddress());
    }

    @Test
    public void testGetStudentAddress_EmptyAddress() {
        student.setStudentaddress("");
        assertEquals("", student.getStudentaddress());
    }
}
