// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Student_set_id_b8adefff49_Test {

    @Test
    public void testSet_id() {
        Student student = new Student();
        String id = "12345";
        student.set_id(id);
        assertEquals(id, student.get_id());
    }

    @Test
    public void testSet_idWithNull() {
        Student student = new Student();
        student.set_id(null);
        assertEquals(null, student.get_id());
    }
}
