// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Student_setMobile_14d728d95e_Test {

    @Mock
    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetMobile_Success() {
        String mobile = "1234567890";
        student.setMobile(mobile);
        assertEquals(mobile, student.getMobile());
    }

    @Test
    public void testSetMobile_Null() {
        String mobile = null;
        student.setMobile(mobile);
        assertEquals(mobile, student.getMobile());
    }
}
