// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Student_get_id_c3fa75ed0b_Test {

    private Student student;

    @BeforeEach
    public void setup() {
        student = new Student();
    }

    @Test
    public void testGetIdWhenIdIsNull() {
        Assertions.assertNull(student.get_id());
    }

    @Test
    public void testGetIdWhenIdIsNotNull() {
        student.set_id("123");
        Assertions.assertEquals("123", student.get_id());
    }
}
