// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Student_setStudentaddress_ae77a1b84a_Test {
    private Student student;

    @BeforeEach
    public void setup() {
        student = new Student();
    }

    @Test
    public void testSetStudentAddress_ValidAddress() {
        String validAddress = "123 Main Street";
        student.setStudentaddress(validAddress);
        Assertions.assertEquals(validAddress, student.getStudentaddress());
    }

    @Test
    public void testSetStudentAddress_NullAddress() {
        String nullAddress = null;
        student.setStudentaddress(nullAddress);
        Assertions.assertNull(student.getStudentaddress());
    }
}
