// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_getMobile_e15a571bc1_Test {

    @Test
    public void testGetMobile() {
        Student student = new Student();
        student.setMobile("1234567890");
        assertEquals("1234567890", student.getMobile());
    }

    @Test
    public void testGetMobile_Empty() {
        Student student = new Student();
        student.setMobile("");
        assertEquals("", student.getMobile());
    }
}
