// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Student_get_id_c3fa75ed0b_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testGetIdWhenIdIsNotNull() {
        String expectedId = "123456";
        student.set_id(expectedId);

        String actualId = student.get_id();

        Assertions.assertEquals(expectedId, actualId, "The id should be " + expectedId);
    }

    @Test
    public void testGetIdWhenIdIsNull() {
        student.set_id(null);

        String actualId = student.get_id();

        Assertions.assertNull(actualId, "The id should be null");
    }
}
