// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Test;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_158c71b90f_Test {

    @Test
    public void testStudentConstructor() {
        String _id = "123";
        String studentname = "John Doe";
        String studentaddress = "123 Main St";
        String mobile = "1234567890";

        Student student = new Student(_id, studentname, studentaddress, mobile);

        assertEquals(_id, student.get_id(), "The id should match the constructor argument");
        assertEquals(studentname, student.getStudentname(), "The student name should match the constructor argument");
        assertEquals(studentaddress, student.getStudentaddress(), "The student address should match the constructor argument");
        assertEquals(mobile, student.getMobile(), "The mobile should match the constructor argument");
    }

    @Test
    public void testStudentConstructorWithNullValues() {
        String _id = null;
        String studentname = null;
        String studentaddress = null;
        String mobile = null;

        Student student = new Student(_id, studentname, studentaddress, mobile);

        assertEquals(_id, student.get_id(), "The id should be null when the constructor argument is null");
        assertEquals(studentname, student.getStudentname(), "The student name should be null when the constructor argument is null");
        assertEquals(studentaddress, student.getStudentaddress(), "The student address should be null when the constructor argument is null");
        assertEquals(mobile, student.getMobile(), "The mobile should be null when the constructor argument is null");
    }
}
