// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Student_getStudentaddress_a74194294e_Test {

    @Test
    public void testGetStudentAddress_ValidAddress() {
        Student student = new Student();
        student.setStudentaddress("123 Main St, Anytown, USA");
        String expectedAddress = "123 Main St, Anytown, USA";
        assertEquals(expectedAddress, student.getStudentaddress());
    }

    @Test
    public void testGetStudentAddress_EmptyAddress() {
        Student student = new Student();
        student.setStudentaddress("");
        String expectedAddress = "";
        assertEquals(expectedAddress, student.getStudentaddress());
    }

}
