// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_toString_ceffa8036e_Test {

    @Test
    public void testToStringMethod() {
        Student student = new Student();
        student.set_id("1");
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Main St");
        student.setMobile("1234567890");

        String expectedOutput = "Student{" +
                "_id='1'" +
                ", studentname='John Doe'" +
                ", studentaddress='123 Main St'" +
                ", mobile='1234567890'" +
                '}';

        assertEquals(expectedOutput, student.toString());
    }

    @Test
    public void testToStringMethodWithNullValues() {
        Student student = new Student();

        String expectedOutput = "Student{" +
                "_id='null'" +
                ", studentname='null'" +
                ", studentaddress='null'" +
                ", mobile='null'" +
                '}';

        assertEquals(expectedOutput, student.toString());
    }
}
