// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Student_setMobile_14d728d95e_Test {

    @Mock
    private Student student;
    
    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        student = new Student();
    }

    @Test
    public void testSetMobile_Success() {
        String expectedMobile = "1234567890";
        student.setMobile(expectedMobile);
        Assertions.assertEquals(expectedMobile, student.getMobile());
    }

    @Test
    public void testSetMobile_Null() {
        String expectedMobile = null;
        student.setMobile(expectedMobile);
        Assertions.assertNull(student.getMobile());
    }
}
