// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Student_Student_4f0c49de05_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testStudentInstanceNotNull() {
        assertNotNull(student, "Student instance should not be null");
    }

    @Test
    public void testStudentDefaultValues() {
        assertNull(student.getId(), "Default id should be null");
        assertNull(student.getName(), "Default name should be null");
        assertEquals(0, student.getAge(), "Default age should be 0");
        assertNull(student.getDepartment(), "Default department should be null");
    }
}
