// Test generated by RoostGPT for test gitlab using AI Type Open AI and AI Model gpt-4-1106-preview

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Student_setStudentaddress_ae77a1b84a_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetStudentaddress_WithValidAddress() {
        String validAddress = "123 Main St";
        student.setStudentaddress(validAddress);
        assertEquals(validAddress, student.getStudentaddress(), "The student address should match the one that was set");
    }

    @Test
    public void testSetStudentaddress_WithNullAddress() {
        student.setStudentaddress(null);
        assertNull(student.getStudentaddress(), "The student address should be null when set to null");
    }
}
