// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Student_getStudentname_b7193f1cfc_Test {

    private Student student;

    @BeforeEach
    public void setup() {
        student = Mockito.mock(Student.class);
    }

    @Test
    public void testGetStudentName() {
        String expectedName = "John Doe";
        Mockito.when(student.getStudentname()).thenReturn(expectedName);
        String actualName = student.getStudentname();
        assertEquals(expectedName, actualName);
    }

    @Test
    public void testGetStudentName_Empty() {
        String expectedName = "";
        Mockito.when(student.getStudentname()).thenReturn(expectedName);
        String actualName = student.getStudentname();
        assertEquals(expectedName, actualName);
    }
}
