// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

public class Student_get_id_c3fa75ed0b_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = Mockito.mock(Student.class);
    }

    @Test
    public void testGetIdSuccess() {
        Mockito.when(student.get_id()).thenReturn("12345");
        String id = student.get_id();
        assertEquals("12345", id);
    }

    @Test
    public void testGetIdFailure() {
        Mockito.when(student.get_id()).thenReturn(null);
        String id = student.get_id();
        assertEquals(null, id);
    }
}
