// Test generated by RoostGPT for test gitlab using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class Student_setStudentname_e4841ead99_Test {

    private Student student;

    @Before
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetStudentNameValid() {
        String expectedStudentName = "John Doe";
        student.setStudentname(expectedStudentName);
        Assert.assertEquals(expectedStudentName, student.getStudentname());
    }

    @Test
    public void testSetStudentNameNull() {
        student.setStudentname(null);
        Assert.assertNull(student.getStudentname());
    }
}
