// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
public class Student_Student_4f0c49de05_Test {

    @Test
    public void testStudentConstructor() {
        Student student = new Student();
        assertNotNull(student);
    }

    @Test
    public void testStudentConstructorWithParameters() {
        Student student = new Student("John", "Doe", 20, "CS");
        assertNotNull(student);
        assertEquals("John", student.getFirstName());
        assertEquals("Doe", student.getLastName());
        assertEquals(20, student.getAge());
        assertEquals("CS", student.getMajor());
    }
}
