// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Entity;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Student_getStudentname_b7193f1cfc_Test {

    @Test
    public void testGetStudentName() {
        // TODO: Replace with the actual student instance
        Student student = new Student();
        String expectedName = "John Doe";

        student.setStudentname(expectedName);
        String actualName = student.getStudentname();

        Assertions.assertEquals(expectedName, actualName);
    }

    @Test
    public void testGetStudentName_Empty() {
        // TODO: Replace with the actual student instance
        Student student = new Student();
        String expectedName = "";

        student.setStudentname(expectedName);
        String actualName = student.getStudentname();

        Assertions.assertEquals(expectedName, actualName);
    }
}
