// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class StudentController_saveStudent_5bf7dc525f_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @Test
    public void testSaveStudent_Success() {
        Student student = new Student();
        student.set_id("123");
        when(studentServices.saveorUpdate(student)).thenReturn(student.get_id());

        String result = studentController.saveStudent(student);
        Assertions.assertEquals("123", result);
    }

    @Test
    public void testSaveStudent_Failure() {
        Student student = new Student();
        student.set_id("123");
        when(studentServices.saveorUpdate(student)).thenReturn(null);

        String result = studentController.saveStudent(student);
        Assertions.assertNull(result);
    }
}
