// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;

class StudentController_update_7f4e3cda7f_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void testUpdateStudentSuccess() {
        Student student = new Student();
        student.set_id("123");
        student.setStudentName("John");
        student.setStudentAddress("New York");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(student);

        Student result = studentController.update(student, "123");
        verify(studentServices, times(1)).saveorUpdate(student);

        assertEquals("123", result.get_id());
        assertEquals("John", result.getStudentName());
        assertEquals("New York", result.getStudentAddress());
        assertEquals("1234567890", result.getMobile());
    }

    @Test
    void testUpdateStudentFailure() {
        Student student = new Student();
        student.set_id("123");
        student.setStudentName("John");
        student.setStudentAddress("New York");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(null);

        Student result = studentController.update(student, "123");
        verify(studentServices, times(1)).saveorUpdate(student);

        assertNull(result);
    }
}
