// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class StudentController_getStudents_34b847f697_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @Test
    public void testGetStudents() {
        String studentId = "12345"; // TODO: Change this to the actual student ID
        Student expectedStudent = new Student();
        expectedStudent.set_id(studentId);
        when(studentServices.getStudentByID(studentId)).thenReturn(expectedStudent);

        Student actualStudent = studentController.getStudents(studentId);
        assertEquals(expectedStudent, actualStudent);
    }

    @Test
    public void testGetStudentsWhenNoStudentFound() {
        String studentId = "12345"; // TODO: Change this to the actual student ID
        when(studentServices.getStudentByID(studentId)).thenReturn(null);

        Student actualStudent = studentController.getStudents(studentId);
        assertEquals(null, actualStudent);
    }
}
