// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class StudentController_getStudents_34b847f697_Test {

    @InjectMocks
    private StudentController studentController;

    @Mock
    private StudentServices studentServices;

    @Test
    public void testGetStudents_success() {
        Student student = new Student();
        student.set_id("123");
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");

        when(studentServices.getStudentByID("123")).thenReturn(student);

        Student result = studentController.getStudents("123");

        assertEquals("123", result.get_id());
        assertEquals("John Doe", result.getStudentname());
        assertEquals("123 Street", result.getStudentaddress());
        assertEquals("1234567890", result.getMobile());
    }

    @Test
    public void testGetStudents_failure() {
        when(studentServices.getStudentByID("123")).thenReturn(null);

        Student result = studentController.getStudents("123");

        assertEquals(null, result);
    }
}
