// Test generated by RoostGPT for test gitlab using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class StudentController_update_7f4e3cda7f_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testUpdate() {
        Student student = new Student();
        student.set_id("123");
        student.setName("John Doe");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(student);

        Student result = studentController.update(student, "123");

        verify(studentServices, times(1)).saveorUpdate(student);
        assertEquals("123", result.get_id());
        assertEquals("John Doe", result.getName());
    }

    @Test
    public void testUpdate_NullId() {
        Student student = new Student();
        student.setName("John Doe");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(student);

        Student result = studentController.update(student, null);

        verify(studentServices, times(1)).saveorUpdate(student);
        assertEquals(null, result.get_id());
        assertEquals("John Doe", result.getName());
    }
}
