/*
Test generated by RoostGPT for test aman321 using AI Type Open AI and AI Model gpt-4

1. Positive Scenario: Delete Student with Valid ID
   Test the deleteStudent function with a valid student ID that exists in the database. The student record should be successfully removed from the database.

2. Negative Scenario: Delete Student with Invalid ID
   Test the deleteStudent function with an invalid student ID that does not exist in the database. The function should handle this gracefully, ideally returning an error message or exception indicating that the student ID does not exist.

3. Negative Scenario: Delete Student with Null ID
   Test the deleteStudent function with a null ID. The function should return an error or exception indicating that the student ID cannot be null.

4. Negative Scenario: Delete Student with Empty String ID
   Test the deleteStudent function with an empty string as the student ID. The function should return an error or exception indicating that the student ID cannot be an empty string.

5. Positive Scenario: Delete Student Twice
   Test the deleteStudent function with a valid student ID, then attempt to delete the same student ID again. The first deletion should succeed while the second deletion should return an error message or exception indicating that the student ID does not exist.

6. Positive Scenario: Delete Multiple Students
   Test the deleteStudent function with multiple valid student IDs one after the other. All student records should be successfully removed from the database.

7. Negative Scenario: Delete Student with Special Characters in ID
   Test the deleteStudent function with a student ID that contains special characters. The function should return an error or exception indicating that the student ID is not valid.

8. Negative Scenario: Delete Student with ID that Exceeds Maximum Length
   Test the deleteStudent function with a student ID that exceeds the maximum allowed length. The function should return an error or exception indicating that the student ID is too long. 

9. Boundary Scenario: Delete Student at the Limits
   Test the deleteStudent function with the highest and lowest possible student IDs (if there's a defined limit). The function should handle these edge cases correctly.
*/
<dependencies>
    <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>3.11.0</version>
        <scope>test</scope>
    </dependency>
</dependencies>
