// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

public class StudentController_saveStudent_d0ac6d7812_Test {

    @InjectMocks
    private StudentController studentController;

    @Mock
    private StudentServices studentServices;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSaveStudent_Success() {
        Student student = new Student();
        student.set_id("1234");
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(student)).thenReturn(student);

        String result = studentController.saveStudent(student);
        assertEquals("1234", result);

        verify(studentServices).saveorUpdate(student);
    }

    @Test
    public void testSaveStudent_Failure() {
        Student student = new Student();
        student.set_id("1234");
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(student)).thenReturn(null);

        String result = studentController.saveStudent(student);
        assertEquals(null, result);

        verify(studentServices).saveorUpdate(student);
    }
}
