// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class StudentController_getStudents_88425bb65e_Test {

    @InjectMocks
    private StudentController studentController;

    @Mock
    private StudentServices studentServices;

    @BeforeEach
    void setMockOutput() {
        when(studentServices.getStudentByID("123")).thenReturn(new Student("123", "John", "NY", "1234567890"));
        when(studentServices.getStudentByID("")).thenReturn(null);
    }

    @Test
    public void testGetStudents_validId() {
        Student result = studentController.getStudents("123");
        assertEquals("123", result.get_id());
        assertEquals("John", result.getStudentname());
        assertEquals("NY", result.getStudentaddress());
        assertEquals("1234567890", result.getMobile());
    }

    @Test
    public void testGetStudents_emptyId() {
        Student result = studentController.getStudents("");
        assertEquals(null, result);
    }
}
