// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

@SpringBootTest
public class StudentController_deleteStudent_163c0d34c8_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void deleteStudentTest_ValidId() {
        String id = "12345";
        studentController.deleteStudent(id);

        verify(studentServices, times(1)).deleteStudent(id);
    }

    @Test
    public void deleteStudentTest_InvalidId() {
        String id = "";
        studentController.deleteStudent(id);

        verify(studentServices, times(1)).deleteStudent(id);
    }
}
