// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class StudentController_saveStudent_5bf7dc525f_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSaveStudent() {
        Student student = new Student();
        student.set_id("123");
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(student);

        String result = studentController.saveStudent(student);
        assertEquals("123", result);

        verify(studentServices, times(1)).saveorUpdate(student);
    }

    @Test
    public void testSaveStudentNullId() {
        Student student = new Student();
        student.set_id(null);
        student.setStudentname("John Doe");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(student);

        String result = studentController.saveStudent(student);
        assertEquals(null, result);

        verify(studentServices, times(1)).saveorUpdate(student);
    }
}
