// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class StudentController_update_44931af386_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testUpdateStudentSuccess() {
        Student student = new Student();
        student.set_id("123");
        student.setStudentname("John");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(student);

        Student result = studentController.update(student, "123");

        assertEquals("123", result.get_id());
        assertEquals("John", result.getStudentname());
        assertEquals("123 Street", result.getStudentaddress());
        assertEquals("1234567890", result.getMobile());

        verify(studentServices, times(1)).saveorUpdate(student);
    }

    @Test
    public void testUpdateStudentFailure() {
        Student student = new Student();
        student.set_id("123");
        student.setStudentname("John");
        student.setStudentaddress("123 Street");
        student.setMobile("1234567890");

        when(studentServices.saveorUpdate(any(Student.class))).thenReturn(null);

        Student result = studentController.update(student, "123");

        assertEquals(null, result);

        verify(studentServices, times(1)).saveorUpdate(student);
    }
}
