// Test generated by RoostGPT for test gitlab using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

class StudentController_saveStudent_d0ac6d7812_Test {

    @InjectMocks
    StudentController studentController;

    @Mock
    StudentServices studentServices;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void testSaveStudent() {
        Student student = new Student();
        student.set_id("123");
        when(studentServices.saveorUpdate(student)).thenReturn(student);

        String result = studentController.saveStudent(student);
        assertEquals("123", result);
    }

    @Test
    void testSaveStudentWithNullId() {
        Student student = new Student();
        when(studentServices.saveorUpdate(student)).thenReturn(student);

        String result = studentController.saveStudent(student);
        assertEquals(null, result);
    }
}
