// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package com.example.SpringMongoProject.Controller;

import com.example.SpringMongoProject.Entity.Student;
import com.example.SpringMongoProject.Service.StudentServices;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.test.context.SpringBootTest;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
@ExtendWith(MockitoExtension.class)
public class StudentController_getStudents_23978b7130_Test {

    @InjectMocks
    private StudentController studentController;

    @Mock
    private StudentServices studentServices;

    private List<Student> studentList;

    @BeforeEach
    void setUp() {
        studentList = Arrays.asList(new Student(), new Student());
    }

    @Test
    public void testGetStudentsSuccess() {
        when(studentServices.listAll()).thenReturn(studentList);
        Iterable<Student> result = studentController.getStudents();
        assertEquals(studentList, result, "Expected and actual students should match");
    }

    @Test
    public void testGetStudentsFailure() {
        when(studentServices.listAll()).thenReturn(null);
        Iterable<Student> result = studentController.getStudents();
        assertEquals(null, result, "Expected and actual students should match");
    }
}
