// Test generated by RoostGPT for test restAssuredTesting using AI Type Open AI and AI Model gpt-4


// Test generated for /laureate/{laureateID}_get for http method type GET in rest-assured framework


// RoostTestHash=81e2a40d4b


package com.example.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class laureate_laureateIDGetTest {
  
    @Test  
    public void laureate_laureateID_get_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src/test/java/com/example/RoostTest/laureate_laureateIDGetTest.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("laureateID", map.get("laureateID") != null ? map.get("laureateID") : "")
                .when()
                .get("/laureate/{laureateID}")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: Successful call of Laureate given the ID");
    
              if (response.jsonPath().get("laureate") != null) {    
              if (response.jsonPath().get("laureate.id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.id"), instanceOf(Integer.class));  
                MatcherAssert.assertThat(response.jsonPath().getDouble("laureate.id"), greaterThanOrEqualTo(1));
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.knownName") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.knownName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.knownName.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.knownName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.knownName.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.knownName.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.knownName.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.givenName") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.givenName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.givenName.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.givenName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.givenName.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.givenName.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.givenName.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.familyName") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.familyName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.familyName.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.familyName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.familyName.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.familyName.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.familyName.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.fullName") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.fullName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.fullName.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.fullName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.fullName.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.fullName.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.fullName.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.filename") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.filename"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.penname") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.penname"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.gender") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.gender"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("laureate.laureateIfPerson.gender"), anyOf(equalTo("female"), equalTo("male")));
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.date"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.city") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.city.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.city.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.city.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.city.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.country") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.country.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.country.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.country.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.country.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.cityNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfPerson.birth.place.cityNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfPerson.birth.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.countryNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfPerson.birth.place.countryNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfPerson.birth.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.continent") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.continent.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.continent.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.continent.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.continent.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.locationString") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.locationString.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.locationString.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.birth.place.locationString.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.birth.place.locationString.no"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.date"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.city") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.city.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.city.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.city.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.city.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.country") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.country.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.country.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.country.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.country.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.cityNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfPerson.death.place.cityNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfPerson.death.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.countryNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfPerson.death.place.countryNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfPerson.death.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.continent") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.continent.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.continent.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.continent.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.continent.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.locationString") != null) {    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.locationString.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.locationString.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfPerson.death.place.locationString.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfPerson.death.place.locationString.no"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.orgName") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.orgName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.orgName.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.orgName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.orgName.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.orgName.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.orgName.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.nativeName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.nativeName"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.acronym") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.acronym"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.date"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.city") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.city.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.city.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.city.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.city.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.country") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.country.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.country.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.country.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.country.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.cityNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfOrg.founded.place.cityNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfOrg.founded.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.countryNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfOrg.founded.place.countryNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfOrg.founded.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.continent") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.continent.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.continent.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.continent.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.continent.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.locationString") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.locationString.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.locationString.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.founded.place.locationString.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.founded.place.locationString.no"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.date"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.city") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.city.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.city.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.city.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.city.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.country") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.country.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.country.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.country.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.country.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.cityNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfOrg.dissolution.place.cityNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfOrg.dissolution.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.countryNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfOrg.dissolution.place.countryNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfOrg.dissolution.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.continent") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.continent.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.continent.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.continent.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.continent.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.locationString") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.locationString.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.locationString.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.locationString.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.dissolution.place.locationString.no"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.city") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.city.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.city.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.city.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.city.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.country") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.country.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.country.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.country.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.country.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.cityNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfOrg.headquarters.cityNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfOrg.headquarters.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.countryNow.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.laureateIfOrg.headquarters.countryNow.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.laureateIfOrg.headquarters.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.continent") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.continent.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.continent.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.continent.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.continent.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.locationString") != null) {    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.locationString.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.locationString.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.laureateIfOrg.headquarters.locationString.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.laureateIfOrg.headquarters.locationString.no"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.wikipedia") != null) {    
              if (response.jsonPath().get("laureate.wikipedia.slug") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.wikipedia.slug"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.wikipedia.english") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.wikipedia.english"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.wikidata") != null) {    
              if (response.jsonPath().get("laureate.wikidata.id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.wikidata.id"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.wikidata.url") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.wikidata.url"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.sameAs") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.sameAs").size(); i++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.sameAs"), instanceOf(List.class));
  
          }
    
              if (response.jsonPath().get("laureate.links") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.links").size(); i++) {    
              if (response.jsonPath().get("laureate.links[`"+ i +"`].rel") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.links[`"+ i +"`].rel"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.links[`"+ i +"`].href") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.links[`"+ i +"`].href"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.links[`"+ i +"`].action") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.links[`"+ i +"`].action"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.links[`"+ i +"`].types") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.links[`"+ i +"`].types"), instanceOf(String.class));  
          }
    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.links"), instanceOf(List.class));
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes") != null) {    
                for (int i = 0; i < response.jsonPath().getList("laureate.nobelPrizes").size(); i++) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].awardYear") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].awardYear"), instanceOf(Integer.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].category") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].category.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].category.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].category.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].category.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].category.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].category.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].categoryFullName") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].categoryFullName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].categoryFullName.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].categoryFullName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].categoryFullName.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].categoryFullName.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].categoryFullName.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].sortOrder") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].sortOrder"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("laureate.nobelPrizes[`"+ i +"`].sortOrder"), anyOf(equalTo("1"), equalTo("2"), equalTo("3")));
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].portion") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].portion"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("laureate.nobelPrizes[`"+ i +"`].portion"), anyOf(equalTo("1"), equalTo("1/2"), equalTo("1/3"), equalTo("1/4")));
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].dateAwarded") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].dateAwarded"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].prizeStatus") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].prizeStatus"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("laureate.nobelPrizes[`"+ i +"`].prizeStatus"), anyOf(equalTo("received"), equalTo("declined"), equalTo("restricted")));
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].motivation") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].motivation.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].motivation.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].motivation.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].motivation.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].motivation.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].motivation.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].prizeAmount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].prizeAmount"), instanceOf(Integer.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].prizeAmountAdjusted") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].prizeAmountAdjusted"), instanceOf(Integer.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations") != null) {    
                for (int i1 = 0; i1 < response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].affiliations").size(); i1++) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].name") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].name.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].name.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].name.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].name.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].name.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].name.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nameNow") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nameNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nameNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nameNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nameNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nameNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nameNow.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nativeName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].nativeName"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].city") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].city.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].city.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].city.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].city.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].country") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].country.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].country.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].country.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].country.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.sameAs") != null) {    
                for (int i11 = 0; i11 < response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.sameAs").size(); i11++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.sameAs") != null) {    
                for (int i11 = 0; i11 < response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.sameAs").size(); i11++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].locationString") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].locationString.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].locationString.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].locationString.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].affiliations[`"+ i1 +"`].locationString.no"), instanceOf(String.class));  
          }
  
          }
    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].affiliations"), instanceOf(List.class));
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences") != null) {    
                for (int i1 = 0; i1 < response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].residences").size(); i1++) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].city") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].city.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].city.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].city.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].city.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].country") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].country.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].country.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].country.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].country.no"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.sameAs") != null) {    
                for (int i11 = 0; i11 < response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.sameAs").size(); i11++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.no"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.sameAs") != null) {    
                for (int i11 = 0; i11 < response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.sameAs").size(); i11++) {    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].locationString") != null) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].locationString.en"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].locationString.se"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].locationString.no") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].residences[`"+ i1 +"`].locationString.no"), instanceOf(String.class));  
          }
  
          }
    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].residences"), instanceOf(List.class));
  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links") != null) {    
                for (int i1 = 0; i1 < response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].links").size(); i1++) {    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].rel") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].rel"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].href") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].href"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].action") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].action"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].types") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureate.nobelPrizes[`"+ i +"`].links[`"+ i1 +"`].types"), instanceOf(String.class));  
          }
    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes[`"+ i +"`].links"), instanceOf(List.class));
  
          }
    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("laureate.nobelPrizes"), instanceOf(List.class));
  
          }
  
          }
				}
if (response.statusCode() == 400) {
					System.out.println("Description: Bad request.The request could not be understood by the server due to malformed syntax, modifications needed.");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 404) {
					System.out.println("Description: Not Found. The requested resource could not be found but may be available again in the future.");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 422) {
					System.out.println("Description: Unprocessable Entity. The request was well-formed but was unable to be followed due to semantic errors.");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
